# SwiftLint Configuration
# https://github.com/realm/SwiftLint

# Paths to include/exclude
included:
  - Sources

excluded:
  - .build
  - .swiftpm

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - sorted_first_last
  - vertical_whitespace_opening_braces

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 8
  error: 10

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000

# Reporter
reporter: "xcode"
