name: Install
description: Validate
runs:
  using: composite
  steps:
    - name: format:check
      run: bun prettier:check
      shell: bash

    - name: lint
      run: bun lint:check
      shell: bash

    - name: tsc
      run: bun ts:check
      shell: bash

    - name: test
      run: bun test
      shell: bash
