name: Validate
description: Validate
runs:
  using: composite
  steps:
    - name: Run SwiftLint
      shell: bash
      run: swiftlint

    - name: Build functions
      shell: bash
      run: swift build -c release
