name: Install
description: Validate
runs:
  using: composite
  steps:
    - name: Build main lambda
      shell: bash
      working-directory: apps/lho-lambda
      run: dotnet build --configuration Release --no-restore

    - name: Build authorizer lambda
      shell: bash
      working-directory: apps/lho-authorizer
      run: dotnet build --configuration Release --no-restore
