name: Install
description: Install dependencies
runs:
  using: composite
  steps:
    - name: Install moreutils
      run: sudo apt install moreutils
      shell: bash

    # https://github.com/actions/virtual-environments/issues/1187
    - name: tune linux network
      run: sudo ethtool -K eth0 tx off rx off
      shell: bash

    - name: Ensure branch is rebased with main
      run: git stash && git pull --rebase
      shell: bash

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Restore .NET dependencies for main lambda
      shell: bash
      working-directory: apps/lho-lambda/src
      run: dotnet restore

    - name: Restore .NET dependencies for authorizer
      shell: bash
      working-directory: apps/lho-authorizer/src
      run: dotnet restore

    # https://github.com/actions/virtual-environments/issues/1187
    - name: tune linux network
      run: sudo ethtool -K eth0 tx off rx off
      shell: bash

    - name: 🥟 Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: Setup Node
      uses: actions/setup-node@v4.1.0
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Check commit message
      shell: bash
      run: bun commitlint --from=HEAD^1
