name: Install
description: Install dependencies
runs:
  using: composite
  steps:
    - name: Ensure branch is rebased with main
      run: git stash && git pull --rebase
      shell: bash

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"

    - name: Restore dependencies
      shell: bash
      run: dotnet restore Lho.Lambda.slnx

    - name: Build
      shell: bash
      run: |
        dotnet build src/Lho.Lambda/Lho.Lambda.csproj --no-restore
        dotnet build src/Lho.Lambda.Authorizer/Lho.Lambda.Authorizer.csproj --no-restore
        dotnet build src/Lho.Lambda.Local/Lho.Lambda.Local.csproj --no-restore

    - name: Test
      shell: bash
      run: dotnet test src/Lho.Lambda.Tests/Lho.Lambda.Tests.csproj --no-restore
