name: Changelogs
description: Generate changelogs and manage versions using conventional commits
inputs:
  create_tag:
    description: "Whether to create a git tag"
    required: false
    default: "false"
  push_changes:
    description: "Whether to push changes to repository"
    required: false
    default: "false"
outputs:
  version:
    description: "The new version number"
    value: ${{ steps.version.outputs.version }}
  version_tag:
    description: "The new version tag"
    value: ${{ steps.version.outputs.version_tag }}
  release_type:
    description: "The type of release (major, minor, patch)"
    value: ${{ steps.version.outputs.release_type }}
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Make scripts executable
      shell: bash
      run: |
        chmod +x scripts/changelog.sh
        chmod +x scripts/version.sh

    - name: Generate version info
      id: version
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        ./scripts/version.sh info
        echo "version=$(./scripts/version.sh get)" >> $GITHUB_OUTPUT
        echo "version_tag=$(./scripts/version.sh get-tag)" >> $GITHUB_OUTPUT
        echo "git_sha=$(./scripts/version.sh get-sha)" >> $GITHUB_OUTPUT

    - name: Generate changelog
      shell: bash
      run: |
        if [ "${{ inputs.create_tag }}" = "true" ]; then
          ./scripts/changelog.sh --tag
        else
          ./scripts/changelog.sh
        fi

    - name: Update .NET project versions
      shell: bash
      run: ./scripts/version.sh update

    - name: Configure Git
      shell: bash
      if: ${{ inputs.push_changes == 'true' }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Push changes
      shell: bash
      if: ${{ inputs.push_changes == 'true' }}
      run: |
        git add .
        git commit -m "chore(release): update changelogs and versions [skip ci]" || true
        git push origin HEAD --follow-tags
